# Copyright 2018 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a Apache-style
# license that can be found in the LICENSE file.

ConfDir = "./conf.d"
Interval = 10
Debug = true
