# Copyright 2018 The OpenPitrix Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

[template]
src = "simple.json.tmpl"
dest = "simple.json"

check_cmd = """
	make -C ${LIBCONFD_CONFDIR}/apps/simple check
"""

reload_cmd = """
	make -C ${LIBCONFD_CONFDIR}/apps/simple restart
"""
